name: final_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  go_router: ^6.0.0
  http: ^1.2.1
  image_picker: ^0.8.4+5
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/tr.json

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true
